### ISSUE TITLE
can we rename the repo to be all lowercase?

### ISSUE THREAD

**Issue by indera** [ctsit/mdat#1]

**Comment by pbchase** [comment]
At the very least we will do that. The mixed case thing it annoying.  

On that note, I would love for the repo to have a name that rolls off the tongue a little better.  The current acronym is supposed to mean "Medical Engine for Decision Assistance & Support". It doesn't have to be medical.  What we are writing is completely generic.  

We return the best alternative of N alternatives given N x M responses to N criteria. Our reference example is about colorectal cancer screening, but we could use this to guide your choice for lunch.  Do you want to eat at Tony's Italian, Zorba's Greek, Juanita's Mexican, or Angelo's Cuban?  The selection criteria are cost, distance, atmosphere, average review, number of reviews, and waiting time.  This algorithm could be used to pick a restaurant for you. We could as easily call it "Lunch Engine for Decision Assistance & Support" (LEDAS).

Maybe "Decision Aid Tool" (DAT)? "Decision Aid Library" (DAL)?

Suggestions?

**Comment by indera** [comment]
DecAs - Decision Assistant?

**Comment by pbchase** [comment]
Repo renamed! we are now "mdat"
